# Generated by Django 4.1.3 on 2022-12-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo_dos', '0004_mensaje_rename_user_avatar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='User',
            new_name='user',
        ),
    ]
